/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.threeD;

import org.openide.util.NbBundle;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class AddGeoCPMDialogPanel extends javax.swing.JPanel {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkDynamic;
    private javax.swing.JCheckBox chkStatic;
    private javax.swing.JLabel lblWhichResults;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form AddGeoCPMDialogPanel.
     */
    public AddGeoCPMDialogPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isStatic() {
        return chkStatic.isSelected();
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isDynamic() {
        return chkDynamic.isSelected();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblWhichResults = new javax.swing.JLabel();
        chkStatic = new javax.swing.JCheckBox();
        chkDynamic = new javax.swing.JCheckBox();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        lblWhichResults.setText(NbBundle.getMessage(
                AddGeoCPMDialogPanel.class,
                "AddGeoCPMDialogPanel.lblWhichResults.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblWhichResults, gridBagConstraints);

        chkStatic.setText(NbBundle.getMessage(AddGeoCPMDialogPanel.class, "AddGeoCPMDialogPanel.chkStatic.text")); // NOI18N
        chkStatic.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(chkStatic, gridBagConstraints);

        chkDynamic.setText(NbBundle.getMessage(AddGeoCPMDialogPanel.class, "AddGeoCPMDialogPanel.chkDynamic.text")); // NOI18N
        chkDynamic.setContentAreaFilled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(chkDynamic, gridBagConstraints);
    }                                                                                                                // </editor-fold>//GEN-END:initComponents
}
