/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
package de.cismet.cids.custom.sudplan.threeD;

import org.apache.log4j.Logger;

import org.openide.util.NbBundle;

/**
 * DOCUMENT ME!
 *
 * @author   mscholl
 * @version  $Revision$, $Date$
 */
public class AddLayerDialogPanel extends javax.swing.JPanel {

    //~ Static fields/initializers ---------------------------------------------

    /** LOGGER. */
    private static final transient Logger LOG = Logger.getLogger(AddLayerDialogPanel.class);

    //~ Instance fields --------------------------------------------------------

    private final transient String layerName;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgpLayerHeight;
    private javax.swing.JLabel lblLayerTypeMessage;
    private javax.swing.JLabel lblMetersASL;
    private javax.swing.JLabel lblOpacity;
    private javax.swing.JLabel lblPercent;
    private javax.swing.JRadioButton rdbHeightLayer;
    private javax.swing.JRadioButton rdbTextureLayer;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtOpacity;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates new form AddLayerDialogPanel.
     *
     * @param  layerName  DOCUMENT ME!
     */
    public AddLayerDialogPanel(final String layerName) {
        this.layerName = layerName;

        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public boolean isTextureLayer() {
        return rdbTextureLayer.isSelected();
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public int getLayerHeight() {
        try {
            return Integer.parseInt(txtHeight.getText());
        } catch (final Exception e) {
            LOG.warn("cannot parse height: " + txtHeight.getText(), e); // NOI18N
            // this is the default
            return 200;
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    public double getOpacity() {
        try {
            final Integer opacity = Integer.parseInt(txtOpacity.getText());

            return opacity / 100d;
        } catch (final Exception e) {
            LOG.warn("cannot parse opacity: " + txtOpacity.getText(), e); // NOI18N
            // this is the default
            return 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bgpLayerHeight = new javax.swing.ButtonGroup();
        rdbTextureLayer = new javax.swing.JRadioButton();
        rdbHeightLayer = new javax.swing.JRadioButton();
        lblLayerTypeMessage = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        lblMetersASL = new javax.swing.JLabel();
        lblOpacity = new javax.swing.JLabel();
        txtOpacity = new javax.swing.JTextField();
        lblPercent = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        bgpLayerHeight.add(rdbTextureLayer);
        rdbTextureLayer.setSelected(true);
        rdbTextureLayer.setText(NbBundle.getMessage(
                AddLayerDialogPanel.class,
                "AddLayerDialogPanel.rdbTextureLayer.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(rdbTextureLayer, gridBagConstraints);

        bgpLayerHeight.add(rdbHeightLayer);
        rdbHeightLayer.setText(NbBundle.getMessage(
                AddLayerDialogPanel.class,
                "AddLayerDialogPanel.rdbHeightLayer.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(rdbHeightLayer, gridBagConstraints);

        lblLayerTypeMessage.setText(NbBundle.getMessage(
                AddLayerDialogPanel.class,
                "AddLayerDialogPanel.lblLayerTypeMessage.text",
                layerName)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblLayerTypeMessage, gridBagConstraints);

        txtHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtHeight.setText(NbBundle.getMessage(AddLayerDialogPanel.class, "AddLayerDialogPanel.txtHeight.text")); // NOI18N
        txtHeight.setMaximumSize(new java.awt.Dimension(50, 28));
        txtHeight.setMinimumSize(new java.awt.Dimension(38, 28));
        txtHeight.setPreferredSize(new java.awt.Dimension(50, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        add(txtHeight, gridBagConstraints);

        lblMetersASL.setText(NbBundle.getMessage(AddLayerDialogPanel.class, "AddLayerDialogPanel.lblMetersASL.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 5);
        add(lblMetersASL, gridBagConstraints);

        lblOpacity.setText(NbBundle.getMessage(
                AddLayerDialogPanel.class,
                "AddLayerDialogPanel.lblOpacity.text",
                layerName)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblOpacity, gridBagConstraints);

        txtOpacity.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtOpacity.setText(NbBundle.getMessage(
                AddLayerDialogPanel.class,
                "AddLayerDialogPanel.txtOpacity.text",
                layerName)); // NOI18N
        txtOpacity.setMaximumSize(new java.awt.Dimension(40, 28));
        txtOpacity.setMinimumSize(new java.awt.Dimension(40, 28));
        txtOpacity.setPreferredSize(new java.awt.Dimension(40, 28));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        add(txtOpacity, gridBagConstraints);

        lblPercent.setText(NbBundle.getMessage(
                AddLayerDialogPanel.class,
                "AddLayerDialogPanel.lblPercent.text",
                layerName)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 2, 5, 5);
        add(lblPercent, gridBagConstraints);
    }                        // </editor-fold>//GEN-END:initComponents
}
